# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_presentation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(203, 216)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setStyleSheet("background-color: rgb(58, 196, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.titre_mouvement = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titre_mouvement.setFont(font)
        self.titre_mouvement.setObjectName("titre_mouvement")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.titre_mouvement)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_3 = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.position_X = QtWidgets.QLineEdit(self.splitter)
        self.position_X.setObjectName("position_X")
        self.position_Y = QtWidgets.QLineEdit(self.splitter)
        self.position_Y.setObjectName("position_Y")
        self.position_Z = QtWidgets.QLineEdit(self.splitter_3)
        self.position_Z.setObjectName("position_Z")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.splitter_3)
        self.bouton_VERRE = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bouton_VERRE.setFont(font)
        self.bouton_VERRE.setStyleSheet("background-color: rgb(255, 247, 5);")
        self.bouton_VERRE.setObjectName("bouton_VERRE")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.bouton_VERRE)
        self.bouton_ESTOP = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bouton_ESTOP.setFont(font)
        self.bouton_ESTOP.setStyleSheet("background-color: rgb(255, 18, 2);")
        self.bouton_ESTOP.setObjectName("bouton_ESTOP")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.bouton_ESTOP)
        self.bouton_GO = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bouton_GO.setFont(font)
        self.bouton_GO.setStyleSheet("background-color: rgb(47, 255, 88);")
        self.bouton_GO.setObjectName("bouton_GO")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bouton_GO)
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 203, 18))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "test"))
        self.titre_mouvement.setText(_translate("MainWindow", "Mouvement du Robot"))
        self.label_3.setText(_translate("MainWindow", "Position Z :"))
        self.label_2.setText(_translate("MainWindow", "Position Y :"))
        self.label.setText(_translate("MainWindow", "Position X :"))
        self.bouton_VERRE.setText(_translate("MainWindow", "ALLER AU VERRE"))
        self.bouton_ESTOP.setText(_translate("MainWindow", "ESTOP"))
        self.bouton_GO.setText(_translate("MainWindow", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
